@@ -45,6 +45,7 @@ jobs:
          wget https://github.com/XTLS/Xray-core/releases/download/v1.5.4/Xray-linux-64.zip
          unzip Xray-linux-64.zip
          rm -f Xray-linux-64.zip
          mv xray xray-linux-amd64
          cd ..
          cd ..
      - name: package
@@ -82,6 +83,7 @@ jobs:
          wget https://github.com/XTLS/Xray-core/releases/download/v1.5.4/Xray-linux-arm64-v8a.zip
          unzip Xray-linux-arm64-v8a.zip
          rm -f Xray-linux-arm64-v8a.zip
          mv xray xray-linux-arm64
          cd ..
          cd ..
      - name: package
@@ -119,6 +121,7 @@ jobs:
          wget https://github.com/XTLS/Xray-core/releases/download/v1.5.4/Xray-linux-s390x.zip
          unzip Xray-linux-s390x.zip
          rm -f Xray-linux-s390x.zip
          mv xray xray-linux-s390x
          cd ..
          cd ..
      - name: package
